fix: Update parameters for github action that posts comments (#163)
The github workflow for posting canbench results is failing due to a
different naming convention in the parameters expected by the github
action we use.

Specifically, there's
[this](https://github.com/Swiss-Subnet/ssn-console/actions/runs/26093916810/job/76726519631)
error message:
```
Warning: Unexpected input(s) 'comment_tag', 'pr_number', valid inputs are ['message', 'file-path', 'github-token', 'reactions', 'pr-number', 'comment-tag', 'mode', 'create-if-not-exists']
Run thollander/actions-comment-pull-request@v3
Error: No issue/pull request in input neither in current context.
```

which can be explained as from [v2 to
v3](https://github.com/thollander/actions-comment-pull-request/blob/e4a76dd2b0a3c2027c3fd84147a67c22ee4c90fa/MIGRATION_GUIDE.md?plain=1#L9)
the parameter naming convention was changed.